// map
// variable_name.map((value,index,actualarray))

let m =[10,20,30,40,50]
let add =m.map((v,i,a)=> v*2)
console.log(add);


// reduce 
// variable_name.reduce((actualarray,element))
let p = [10,20,30,40]
let r = p.reduce((a,e)=>a+e)
console.log(r);

// filter
// variable_name.map((value,index,actualarray))

let a = [15,96,863,755,96,12,364,98,65,66,33,779]
let b =a.filter((e,f,g)=> f>10)
console.log(b);








